export default {
  login: "Yuvraj2172",
  id: 77541888,
  node_id: "MDQ6VXNlcjc3NTQxODg4",
  avatar_url: "https://avatars.githubusercontent.com/u/77541888?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/Yuvraj2172",
  html_url: "https://github.com/Yuvraj2172",
  followers_url: "https://api.github.com/users/Yuvraj2172/followers",
  following_url:
    "https://api.github.com/users/Yuvraj2172/following{/other_user}",
  gists_url: "https://api.github.com/users/Yuvraj2172/gists{/gist_id}",
  starred_url: "https://api.github.com/users/Yuvraj2172/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/Yuvraj2172/subscriptions",
  organizations_url: "https://api.github.com/users/Yuvraj2172/orgs",
  repos_url: "https://api.github.com/users/Yuvraj2172/repos",
  events_url: "https://api.github.com/users/Yuvraj2172/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/Yuvraj2172/received_events",
  type: "User",
  site_admin: false,
  name: "Yuvraj Soni",
  company: null,
  blog: "",
  location: "India",
  email: null,
  hireable: null,
  bio: "Sky is the limit.",
  twitter_username: "demon_roar",
  public_repos: 37,
  public_gists: 0,
  followers: 18,
  following: 28,
  created_at: "2021-01-16T15:50:55Z",
  updated_at: "2023-09-14T18:31:43Z",
};
